server:
  port: ${PORT:8080}

# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3001,http://localhost:3002}
  allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
  allowed-headers: ${CORS_ALLOWED_HEADERS:*}
  allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}

spring:
  application:
    name: tarifit-user-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/tarifit_users}
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 10000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.tarifit.user: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

tarifit:
  services:
    learning:
      url: ${LEARNING_SERVICE_URL:http://localhost:8081}
    content:
      url: ${CONTENT_SERVICE_URL:http://localhost:8082}